FROM ubuntu:18.04

RUN apt-get update
RUN export DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y python3.6
RUN apt-get install -y python3-pip

RUN pip3 install pika
RUN pip3 install redis
RUN pip3 install flask
RUN pip3 install flask-cors
RUN pip3 install requests
RUN pip3 install jsonpickle
RUN pip3 install pandas
RUN pip3 install praw

RUN mkdir /frontend
RUN chmod -R 777 /frontend
WORKDIR /frontend

COPY . /frontend

CMD python3 frontend.py