apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
spec:
  selector:
    matchLabels:
      app: sentiment
  replicas: 3
  template:
    metadata:
      labels:
        app: sentiment
    spec:
      containers:
      - name: master
        image: us.gcr.io/datacenter-292401/docker-sentiment:1.0
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: REDIS_HOST
          value: redis
        ports:
        - containerPort: 6000