apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: couchdb
spec:
  selector:
    matchLabels:
      app: couchdb
  replicas: 1
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: master
        image: arungupta/couchbase:k8s
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        env:
          - name: GET_HOSTS_FROM
            value: dns
        ports:
        - containerPort: 6500