##
## You provide this
##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keywords
spec:
  selector:
    matchLabels:
      app: keywords
  replicas: 3
  template:
    metadata:
      labels:
        app: keywords
    spec:
      containers:
      - name: master
        image: us.gcr.io/wired-rhino-267706/docker-keywords:2.0
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: REDIS_HOST
          value: redis
        ports:
        - containerPort: 7000